services:
  pgdb:
    image: postgres:14
    container_name: POSTGRES
    restart: always
    environment:
      - POSTGRES_USER=fedonyuk
      - POSTGRES_PASSWORD=fedonyuk
      - POSTGRES_DB=postgres03
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

#  test_db:
#    image: postgres:14
#    container_name: TEST_DB
#    restart: always
#    environment:
#      - POSTGRES_USER=test
#      - POSTGRES_PASSWORD=test
#      - POSTGRES_DB=test
#    ports:
#      - '5452:5432'

volumes:
  postgres_data:
